-- Generated by tools/build_crystal_anchor.py; do not hand-edit.
-- #15: the under-barrel crystal tip, local to the launcher's pRocketLauncher
-- node: inverse(compiled node rest world) * measured crystal frame
-- (tools/fixtures/warlock_crystal_anchor.json, engine root metres).
-- Columns are Stingray x/y/z basis and translation. Their 0.01 scale cancels
-- the node's compiled scale-100 wrapper; do not normalize them.
-- +X runs from the crystal's mounting cap to its tip.
return {
	node = "pRocketLauncher",
	x_axis = { -0.00034920053267634355, 0.007567706503749011, 0.006527470969762398 },
	y_axis = { 0.009993901089563504, 0.00026442598526485965, 0.0002280787371460721 },
	z_axis = { 0.0, 0.00653145444533061, -0.007572324796822199 },
	position = { -2.837103875936009e-05, 0.008219532251357926, -0.0003651478812097847 },
}
