#!/usr/bin/env python3
"""Generate utils/doomrocket_crystal_anchor.lua for the #15 crystal flame.

Input: the measured crystal frame (tools/fixtures/warlock_crystal_anchor.json,
engine root metres) and the compiled pRocketLauncher node's rest world
transform, read from the clean build in bundleV2. Output: the same frame local
to that node, in column-vector notation (local = inverse(node) * root_frame),
which carries the 0.01 scale that cancels the node's scale-100 wrapper.

    py -3 tools/build_crystal_anchor.py           # print the Lua anchor
    py -3 tools/build_crystal_anchor.py --check   # verify the committed anchor
"""

import argparse
import json
from pathlib import Path
import sys

ROOT = Path(__file__).resolve().parents[1]
FIXTURE = ROOT / "tools/fixtures/warlock_crystal_anchor.json"
ANCHOR = ROOT / "scripts/mods/doomrocket/utils/doomrocket_crystal_anchor.lua"
sys.path.insert(0, str(ROOT / "tools/tests"))


def compiled_node_world():
    from test_warlock_weapon_pipeline import (
        compiled_bundle_resources, compiled_node_index, compiled_unit_structure, resource_key,
    )
    import hashlib

    data = json.loads(FIXTURE.read_text(encoding="utf-8"))
    payload = compiled_bundle_resources()[resource_key("unit", data["target_resource"])][0][1]
    if hashlib.sha256(payload).hexdigest() != data["reviewed_compiled_unit_sha256"]:
        raise SystemExit("compiled launcher changed; remeasure the crystal before regenerating")
    structure = compiled_unit_structure(payload)
    index = compiled_node_index(structure, data["target_node"])
    if index != data["reviewed_compiled_node_index"]:
        raise SystemExit("pRocketLauncher node index changed")
    return structure.nodes[index].world_transform


def inverse_affine(rows):
    """Inverse of a 4x4 affine matrix given as rows with translation in column 3."""
    a = [list(row[:3]) for row in rows[:3]]
    t = [rows[i][3] for i in range(3)]
    det = (a[0][0] * (a[1][1] * a[2][2] - a[1][2] * a[2][1])
           - a[0][1] * (a[1][0] * a[2][2] - a[1][2] * a[2][0])
           + a[0][2] * (a[1][0] * a[2][1] - a[1][1] * a[2][0]))
    inv = [[0.0] * 3 for _ in range(3)]
    inv[0][0] = (a[1][1] * a[2][2] - a[1][2] * a[2][1]) / det
    inv[0][1] = (a[0][2] * a[2][1] - a[0][1] * a[2][2]) / det
    inv[0][2] = (a[0][1] * a[1][2] - a[0][2] * a[1][1]) / det
    inv[1][0] = (a[1][2] * a[2][0] - a[1][0] * a[2][2]) / det
    inv[1][1] = (a[0][0] * a[2][2] - a[0][2] * a[2][0]) / det
    inv[1][2] = (a[0][2] * a[1][0] - a[0][0] * a[1][2]) / det
    inv[2][0] = (a[1][0] * a[2][1] - a[1][1] * a[2][0]) / det
    inv[2][1] = (a[0][1] * a[2][0] - a[0][0] * a[2][1]) / det
    inv[2][2] = (a[0][0] * a[1][1] - a[0][1] * a[1][0]) / det
    it = [-sum(inv[i][k] * t[k] for k in range(3)) for i in range(3)]
    return inv, it


def local_frame(node_rows, data):
    inv, it = inverse_affine(node_rows)

    def direction(v):
        return [sum(inv[i][k] * v[k] for k in range(3)) for i in range(3)]

    def point(p):
        return [sum(inv[i][k] * p[k] for k in range(3)) + it[i] for i in range(3)]

    return {
        "x_axis": direction(data["frame_x_axis"]),
        "y_axis": direction(data["frame_y_axis"]),
        "z_axis": direction(data["frame_z_axis"]),
        "position": point(data["tip_engine_m"]),
    }


def lua_vector(values):
    return "{ " + ", ".join(repr(float(v)) for v in values) + " }"


def generate(frame):
    return "\n".join((
        "-- Generated by tools/build_crystal_anchor.py; do not hand-edit.",
        "-- #15: the under-barrel crystal tip, local to the launcher's pRocketLauncher",
        "-- node: inverse(compiled node rest world) * measured crystal frame",
        "-- (tools/fixtures/warlock_crystal_anchor.json, engine root metres).",
        "-- Columns are Stingray x/y/z basis and translation. Their 0.01 scale cancels",
        "-- the node's compiled scale-100 wrapper; do not normalize them.",
        "-- +X runs from the crystal's mounting cap to its tip.",
        "return {",
        '\tnode = "pRocketLauncher",',
        f"\tx_axis = {lua_vector(frame['x_axis'])},",
        f"\ty_axis = {lua_vector(frame['y_axis'])},",
        f"\tz_axis = {lua_vector(frame['z_axis'])},",
        f"\tposition = {lua_vector(frame['position'])},",
        "}",
        "",
    ))


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    data = json.loads(FIXTURE.read_text(encoding="utf-8"))
    generated = generate(local_frame(compiled_node_world(), data))
    if args.check:
        if ANCHOR.read_text(encoding="utf-8") != generated:
            raise SystemExit("crystal anchor differs from the fixture and compiled launcher node")
        print("crystal anchor matches the fixture and compiled launcher node")
    else:
        print(generated, end="")


if __name__ == "__main__":
    main()
